--게시판 
CREATE TABLE TBL_BOARD(
				NO 						NUMBER(5) 				PRIMARY KEY,
				TITME 			VARCHAR(1000) NOT NULL,
				WRITER 		VARCHAR(200) 	NOT NULL,
				REG_DATE DATE DEFAULT 	SYSDATE 
);

CREATE SEQUENCE SEQ_TBL_BOARD_NO;

--SELECT * FROM TBL_BOARD;

INSERT INTO TBL_BOARD (NO, TITLE, WRITER, REG_DATE)
	VALUES(SEQ_TBL_BOARD_NO.NEXTVAL)

--CREATE SEQUENCE SEQ_01;
--CREATE SEQUENCE SEQ_02;
--	START WITH 2400001;

--SELECT SEQ_02.NEXTVAL FROM DUAL
	
COMMIT; --물리적으로 저장시키기 위함, DML에서 수정했을때 저장하기 위해 사용함, DDM은 자동커밋이라 필요없음



